### ISSUE TITLE
Unable to read images from a directory in dropbox

### ISSUE THREAD

**Issue by datatales2017** [algorithmiaio/algorithmia-python#11]
foo = client.dir("dropbox+XXXXX://XXXXX")
for entry in foo.list():
    print(entry.path)
    print(entry.url)

Error message below:
DataApiError: Directory iteration failed: b'{"error":{"message":"path not found"}}'

dropbox already linked to Algorithmia

**Comment by peckjon** [comment]
Sounds like there may be a problem with your specific Data Connector.  Send us a message via the chat icon (lower-right) at http://algorithmia.com so we can talk securely please?

**Comment by jamesatha** [comment]
Also, it could be an issue with the api key you are using. Make sure it has read access to that connector

**Comment by datatales2017** [comment]
It is already connected.
