### ISSUE TITLE
Inconsistency: Python client uses env var ALGORITHMIA_API_KEY not ALGORITHMIA_API

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/algorithmia-python#12]
The Python client looks for an environment variable `ALGORITHMIA_API_KEY` to override the default API address: https://github.com/algorithmiaio/algorithmia-python/blob/master/Algorithmia/client.py#L19

All other client implementations which check env look for `ALGORITHMIA_API`

Suggest adding `ALGORITHMIA_API` but retaining `ALGORITHMIA_API_KEY` as well for backward-compatibility

**Comment by pmcq** [comment]
`ALGORITHMIA_API` is for the api endpoint, and `ALGORITHMIA_API_KEY` is for the client key

**Comment by peckjon** [comment]
Y Kant Johnny Read

Yeah, nevermind...
