### ISSUE TITLE
Python 3.4 + upgrade?

### ISSUE THREAD

**Issue by hmd-ana** [algorithmiaio/algorithmia-python#17]
Hi there :) 
Would it be possible to have an upgrade of the python flavors? Currently the Algorithmia client only works with python2 , or 3.3 max. But python is already up to 3.7, and even support for 3.4 will be discontinued soon. 
When do you think it might be possible ?

Thank you in advance.

**Comment by peckjon** [comment]
Hi @hmd-ana !

Do you mean the Python client (this repo, used to **call** our Algorithms), or the Python versions we support for **creating** new Algorithms hosted on http://algorithmia.com ?

The client should be version-agnostic; I'm running 3.7 locally here.  If you're experiencing issues, hit us up at support@algorithmia.com and we'll help get things fixed up.

As to **creating** new hosted algorithms, we currently have 3.5 available, and 3.7 if you pick the "Python 3.x - Beta" option.  We'll clean these names up to make them clearer!

**Comment by hmd-ana** [comment]
HI @peckjon !

Yes, I was referring to the Algorithmia Python client. 
Been trying to use it with Python3.5 and 3.6 and encountering issues. Will try again with the latest version and in case of anything will contact support. 
Cheers!
