### ISSUE TITLE
Algorithmia.errors.DataApiError: unable to get file ... from Hosted Data  

### ISSUE THREAD

**Issue by dattran2346** [algorithmiaio/algorithmia-python#20]
Hi, I have a problem of accessing file in my Hosted Data. Here is the code snippet

```
import Algorithmia

client = Algorithmia.client('sim0b1n3***pxFqn1')
cred_json = client.file("data://.my/models/cred.json").getJson()
```

This works fine when running on my local machine, I use conda env, python3.5.4 as #14. However, when I run this in Algorithmia IDE, I can't access the same file
`Algorithmia.errors.DataApiError: unable to get file .my/models/cred.json - None`

My Algorithm setup is python3, closed source, allow internet access. I use the default api key. The read access of `.my/models/` is public

**Comment by besirkurtulmus** [comment]
Hi @dattran2346,

I've been able to reproduce your error. It looks like a bug.

The good news is that inside the Algorithmia IDE (aka. inside the algorithm), you don't need to provide an API key. It automatically authenticates. Removing the API key should work in your use-case.

I'll go ahead, and label this issue as a bug in the meantime.

**Comment by jamesatha** [comment]
@dattran2346 when you run this inside the Algoirthmia platform, you should not supply an API key. So the link to create the client should look like this:
```
client = Algorithmia.client()
```
